[package]
name = "lab"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
nestrs = { path = "../../nestrs", features = ["csrf", "cookies", "session", "ws", "files", "openapi", "graphql", "cache-redis", "schedule", "microservices-redis", "mongo"] }
mongodb = { version = "3", default-features = false, features = ["compat-3-0-0"] }
nestrs-cqrs = { path = "../../nestrs-cqrs" }
async-trait = "0.1"
linkme = "0.3"
async-graphql = "=7.0.17"
tower-cookies = "0.10"
futures-util = "0.3"
tokio-tungstenite = "0.24"
axum = { workspace = true, features = ["multipart"] }
tokio.workspace = true
serde = { version = "1", features = ["derive"] }
serde_json = "1"
validator = { version = "0.20", features = ["derive"] }
