//! `create_dto`: write a `#[derive(...)] struct` with the user's fields
//! and validators.

use std::fs;
use std::path::Path;

use schemars::JsonSchema;
use serde::{Deserialize, Serialize};

use crate::Result;

use super::ScaffoldReport;

#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
pub struct DtoFieldSpec {
    pub name: String,
    pub ty: String,
    #[serde(default)]
    pub optional: bool,
    #[serde(default)]
    pub validators: Vec<String>,
}

pub fn create_dto(path: &Path, name: &str, fields: &[DtoFieldSpec]) -> Result<ScaffoldReport> {
    if !is_safe_ident(name) {
        return Err(crate::Error::InvalidArgument(format!(
            "DTO name `{name}` is not a valid Rust ident"
        )));
    }
    let mut report = ScaffoldReport::new();
    let content = render_dto(name, fields);
    let out_path = path.join("src").join(format!("{}.rs", snake_case(name)));
    fs::create_dir_all(out_path.parent().unwrap())?;
    fs::write(&out_path, content)?;
    report.created(out_path.to_string_lossy());
    Ok(report)
}

fn render_dto(name: &str, fields: &[DtoFieldSpec]) -> String {
    let mut s = String::new();
    s.push_str("//! DTO generated by `nestrs-mcp`.\n\n");
    s.push_str(
        "use nestrs::dto;\nuse serde::{Deserialize, Serialize};\nuse validator::Validate;\n\n",
    );
    s.push_str("#[derive(Debug, Clone, Serialize, Deserialize, Validate, Default)]\n");
    s.push_str("#[dto(allow_unknown_fields)]\n");
    s.push_str(&format!("pub struct {name} {{\n"));
    for f in fields {
        let opt = if f.optional { "Option<" } else { "" };
        let close = if f.optional { ">" } else { "" };
        s.push_str("    #[serde(default)]\n");
        for v in &f.validators {
            s.push_str(&format!("    {v}\n"));
        }
        s.push_str(&format!("    pub {}: {}{}{},\n", f.name, opt, f.ty, close));
    }
    s.push_str("}\n");
    s
}

fn is_safe_ident(s: &str) -> bool {
    !s.is_empty()
        && s.chars()
            .next()
            .is_some_and(|c| c.is_ascii_alphabetic() || c == '_')
        && s.chars().all(|c| c.is_ascii_alphanumeric() || c == '_')
}

fn snake_case(s: &str) -> String {
    let mut out = String::new();
    for (i, c) in s.chars().enumerate() {
        if c.is_ascii_uppercase() {
            if i > 0 {
                out.push('_');
            }
            out.push(c.to_ascii_lowercase());
        } else {
            out.push(c);
        }
    }
    out
}
