//! `create_module`: write `src/<name>/{mod.rs, controller.rs, service.rs}`
//! and register the new module in the parent `lib.rs`/`main.rs`/`mod.rs`.

use std::fs;
use std::path::Path;

use crate::Result;

use super::ScaffoldReport;

pub fn create_module(path: &Path, name: &str, _transports: &[String]) -> Result<ScaffoldReport> {
    if !is_safe_ident(name) {
        return Err(crate::Error::InvalidArgument(format!(
            "module name `{name}` is not a valid Rust ident"
        )));
    }
    let dir = path.join("src").join(name);
    fs::create_dir_all(&dir)?;
    let mut report = ScaffoldReport::new();

    write(&dir.join("mod.rs"), &render_mod_rs(name), &mut report)?;
    write(
        &dir.join("controller.rs"),
        &render_controller(name),
        &mut report,
    )?;
    write(&dir.join("service.rs"), &render_service(name), &mut report)?;

    // Register the new module in the parent `lib.rs`/`main.rs`/`mod.rs`.
    let parent = path.join("src");
    for candidate in ["lib.rs", "main.rs", "mod.rs"] {
        let p = parent.join(candidate);
        if p.exists() {
            append_module_decl(&p, name, &mut report)?;
            break;
        }
    }

    Ok(report)
}

fn write(path: &Path, content: &str, report: &mut ScaffoldReport) -> Result<()> {
    fs::write(path, content)?;
    report.created(path.to_string_lossy());
    Ok(())
}

fn append_module_decl(path: &Path, name: &str, report: &mut ScaffoldReport) -> Result<()> {
    let decl = format!("pub mod {name};\n");
    let mut current = fs::read_to_string(path).unwrap_or_default();
    if !current.contains(&decl) {
        current.push_str(&decl);
        fs::write(path, current)?;
        report.modified(path.to_string_lossy());
    }
    Ok(())
}

fn is_safe_ident(s: &str) -> bool {
    !s.is_empty()
        && s.chars()
            .next()
            .is_some_and(|c| c.is_ascii_alphabetic() || c == '_')
        && s.chars().all(|c| c.is_ascii_alphanumeric() || c == '_')
}

fn render_mod_rs(name: &str) -> String {
    let cap = capitalize(name);
    format!(
        r#"//! `{name}` module — generated by `nestrs-mcp`.

pub mod controller;
pub mod service;

use nestrs::{{module, Module}};

#[derive(Default, Module)]
#[module(
    controllers = [{cap}Controller],
    providers = [{cap}Service],
    exports = [{cap}Service],
)]
pub struct {cap}Module;
"#
    )
}

fn render_controller(name: &str) -> String {
    let cap = capitalize(name);
    format!(
        r#"use nestrs::{{controller, get, routes}};

#[derive(Default)]
#[controller("/{name}")]
pub struct {cap}Controller;

#[routes]
impl {cap}Controller {{
    #[get("/")]
    pub async fn list(&self) -> &'static str {{
        "list {name}"
    }}
}}
"#
    )
}

fn render_service(name: &str) -> String {
    let cap = capitalize(name);
    format!(
        r#"use nestrs::Injectable;

#[derive(Default, Injectable)]
pub struct {cap}Service {{}}
"#
    )
}

fn capitalize(s: &str) -> String {
    let mut chars = s.chars();
    let Some(first) = chars.next() else {
        return String::new();
    };
    first.to_ascii_uppercase().to_string() + chars.as_str()
}
