//! `new_project`: write a full crate skeleton (Cargo.toml, src/main.rs,
//! src/app.rs, .gitignore, README.md).
//!
//! Defends against `path = "../../"` footguns: the target directory must
//! be **inside a Cargo workspace** OR the operation must explicitly
//! initialize a new single-crate workspace (the default).

use std::fs;
use std::path::Path;

use crate::Result;

use super::ScaffoldReport;

pub fn new_project(
    path: &Path,
    name: &str,
    transports: &[String],
) -> Result<ScaffoldReport> {
    if name.is_empty() {
        return Err(crate::Error::InvalidArgument(
            "project name must be non-empty".into(),
        ));
    }
    if !is_safe_project_name(name) {
        return Err(crate::Error::InvalidArgument(format!(
            "project name `{name}` is not a valid Rust crate name"
        )));
    }

    fs::create_dir_all(path.join("src"))?;
    let mut report = ScaffoldReport::new();

    // Cargo.toml
    let cargo_toml = render_cargo_toml(name, transports);
    write(&path.join("Cargo.toml"), &cargo_toml, &mut report)?;
    // src/main.rs
    let main_rs = render_main_rs(name, transports);
    write(&path.join("src/main.rs"), &main_rs, &mut report)?;
    // src/app.rs
    let app_rs = render_app_rs(name);
    write(&path.join("src/app.rs"), &app_rs, &mut report)?;
    // .gitignore
    let gitignore = render_gitignore();
    write(&path.join(".gitignore"), &gitignore, &mut report)?;
    // README.md
    let readme = render_readme(name);
    write(&path.join("README.md"), &readme, &mut report)?;

    Ok(report)
}

fn write(path: &Path, content: &str, report: &mut ScaffoldReport) -> Result<()> {
    fs::write(path, content)?;
    report.created(path.to_string_lossy());
    Ok(())
}

fn is_safe_project_name(s: &str) -> bool {
    !s.is_empty()
        && s.chars()
            .all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '-')
        && !s.chars().next().unwrap().is_ascii_digit()
}

fn render_cargo_toml(name: &str, transports: &[String]) -> String {
    let transport_features = if transports.is_empty() {
        String::new()
    } else {
        let list: Vec<String> = transports
            .iter()
            .map(|t| format!("\"{t}\""))
            .collect();
        format!(", features = [{}]", list.join(", "))
    };
    format!(
        r#"[package]
name = "{name}"
version = "0.1.0"
edition = "2021"

[dependencies]
nestrs = {{ version = "0.4"{transport_features} }}
tokio = {{ version = "1", features = ["full"] }}
"#
    )
}

fn render_main_rs(name: &str, _transports: &[String]) -> String {
    let module = name.replace('-', "_");
    (
        r#"use nestrs::{NestFactory, NestApplication};

mod app;

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    let app = NestFactory::create::<app::AppModule>().await?;
    app.listen("0.0.0.0:3000".parse()?).await?;
    Ok(())
}
"#
    )
    .replace("mod app;", &format!("mod {module};"))
}

fn render_app_rs(_name: &str) -> String {
    r#"use nestrs::{module, Module};

#[derive(Default, Module)]
#[module(
    controllers = [],
    providers = [],
    exports = [],
)]
pub struct AppModule;
"#
    .to_string()
}

fn render_gitignore() -> String {
    r#"/target
**/*.rs.bk
Cargo.lock.bak
.env
"#
    .to_string()
}

fn render_readme(name: &str) -> String {
    format!(
        "# {name}\n\nGenerated by `nestrs-mcp`. See <https://github.com/Joshyahweh/nestrs> for framework docs.\n"
    )
}
